### ISSUE TITLE
Making it more newbie?

### ISSUE THREAD

**Issue by mikazz** [Kerndog73/Animera#1]
Wish this had a compilled exe, or at least easy readme for non-C people ;))

**Comment by indianakernick** [comment]
You're absolutely right. I've been meaning to do that for a long time. I might release a mac and windows build over the weekend if I have time.

**Comment by indianakernick** [comment]
I made a start on this on sunday. Getting a Windows 10 VM up and running takes a while, especially on my extremely underpowered laptop. I'm in the process of installing Qt which is taking a really long time (about 4 hours in and maybe 20% done). I'm determined to release a beta eventually.

**Comment by mikazz** [comment]
That's quite a lot. What is your laptop specs? Didn't know that qt is that heavy

**Comment by indianakernick** [comment]
Installing Qt usually takes a minute or two outside of a VM because I can download the precompiled binaries with Homebrew. I’m running a Windows 10 VM on a 2013 MacBook Air. The VM has 2GB (of the available 4GB) and 2 cores (of the available 4 cores). I’m building Qt from source and I realise now that I could probably find precompiled binaries if I looked hard enough. It grinds my poor little laptop to a crawl. I really want to release something so I will get this done eventually, it’s just gonna take a while.

**Comment by indianakernick** [comment]
There were some problems with the Qt vcpkg package but those have been resolved now. I have successfully installed Qt on a Windows 10 virtual machine! That was supposed to be the easy part... 😣

**Comment by indianakernick** [comment]
Today I managed to get a macOS virtual machine working. Here's Animera running flawlessly inside a virtual machine:

![10 May 2020](https://user-images.githubusercontent.com/10371177/81495901-cdc1ea00-92f2-11ea-9c62-3b729567bc05.png)

That's a macOS Mojave virtual machine running on a macOS Mojave host. Let that sink in...

I did it to make sure that I haven't messed up something with the dynamic libraries. So, this proves that I could release a macOS version of Animera right now but I won't just yet. I want to get a Windows build working first. Then I'll release an alpha for both macOS and Windows.

**Comment by mikazz** [comment]
How about using python to automate compilation, and decision for platform?

**Comment by indianakernick** [comment]
I'm not sure what you mean

**Comment by indianakernick** [comment]
I've managed to get Animera running in a Windows 10 VM!

![17 May 2020](https://user-images.githubusercontent.com/10371177/82134390-8aa5d080-9836-11ea-92f1-33371a0e5298.png)

I'm having trouble getting the font to load though. There are some problems I want to iron out before I release an alpha.

**Comment by indianakernick** [comment]
I fixed the font issues I was having yesterday. Isn't it beautiful?

![18 May 2020](https://user-images.githubusercontent.com/10371177/82194135-7d234000-9935-11ea-8a20-541db2655148.png)

There's still some issues with regex that stop command line argument parsing from working. I think I'll disable that on Windows just to get the alpha build ready. I'm _not making any promises_ but the alpha might be released this weekend.

**Comment by indianakernick** [comment]
Everything is harder on Windows!

I've spent hours going down the rabbit hole of creating an installer. It's a huge pain in the ass. 

On macOS, installers aren't really necessary most of the time. You can just take an app and drop it into the Applications folder. But even that's not really necessary. You can just run the app without needing to do anything special with it. I created a DMG for the app with is really just a fancy ZIP archive. Not really an installer.

Contrast that with Windows and you need an installer that copies a bunch of files into various places, sets some keys on the registry, adds a shortcut to the desktop, adds an item to the start menu and probably more stuff that I don't know about yet. Worse still, there's not one way to create an installer. There's a bunch of frameworks out there for creating installers. I've settled on NSIS because it seems to be the simplest. Configuring NSIS to install Qt and integrating it with CMake is pretty tricky.

When I got Animera running on Windows, I thought I was really close to done but that was a walk in the park compared to creating the installer.

**Comment by indianakernick** [comment]
Yesterday I made some significant progress on the installer. The installer for Windows sort of works but it's missing some features. I still need to add a file association so that when you double-click on a `.animera` file, Animera will open. I also want to add a dedicated icon for `.animera` files and the Animera application itself (rather than them having the same icon like they do now). I'm busy with exams at the moment so it's still going to be a while. Remember when I said I could get this done in a weekend? 😄

**Comment by indianakernick** [comment]
I've released [version 0.1.0](https://github.com/Kerndog73/Animera/releases/tag/v0.1.0). You can now try this out without having to spend three months making an installer for Windows.
